basePath: /
definitions:
  requestModels.UserLogin:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  requestModels.UserRegister:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
host: localhost:8004
info:
  contact: {}
  description: API Server for Task-plan application
  title: Task-plan API
  version: "1.0"
paths:
  /auth/sign-in:
    post:
      consumes:
      - application/json
      description: login account
      operationId: login-account
      parameters:
      - description: account info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/requestModels.UserLogin'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
      summary: SignIn
      tags:
      - auth
  /auth/sign-up:
    post:
      consumes:
      - application/json
      description: create account
      operationId: create-account
      parameters:
      - description: account info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/requestModels.UserRegister'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
      summary: SignUp
      tags:
      - auth
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
