basePath: /
definitions:
  domain.Group:
    properties:
      levelProgress:
        items:
          $ref: '#/definitions/domain.LevelProgress'
        type: array
      name:
        type: string
      tasks:
        items:
          $ref: '#/definitions/domain.Task'
        type: array
      users:
        items:
          $ref: '#/definitions/domain.User'
        type: array
    type: object
  domain.LevelProgress:
    properties:
      name:
        type: string
    type: object
  domain.Task:
    properties:
      description:
        type: string
      level:
        $ref: '#/definitions/domain.LevelProgress'
      name:
        type: string
    type: object
  domain.User:
    properties:
      email:
        type: string
      groups:
        items:
          $ref: '#/definitions/domain.Group'
        type: array
      name:
        type: string
      password:
        type: string
    type: object
host: localhost:8004
info:
  contact: {}
  description: API Server for Task-plan application
  title: Task-plan API
  version: "1.0"
paths:
  /auth/sign-in:
    post:
      consumes:
      - application/json
      description: login account
      operationId: login-account
      parameters:
      - description: account info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/domain.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
      summary: SignIn
      tags:
      - auth
  /auth/sign-up:
    post:
      consumes:
      - application/json
      description: create account
      operationId: create-account
      parameters:
      - description: account info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/domain.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
      summary: SignUp
      tags:
      - auth
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
